app:
  name: "University Leipzig RAG Chat"
  version: "1.0.0"
  debug: true

chroma:
  persist_directory: "./data/chroma_db"
  collection_name: "university_regulations"

ollama:
  base_url: "http://localhost:11434"
  model: "llama2:7b"
  temperature: 0.1
  max_tokens: 2048

documents:
  base_directories:
    - path: "data/pdfs"
      category: "regulations"
      display_name: "Universitäts-Regelungen"
  processing:
    chunk_size: 500
    chunk_overlap: 50
    max_file_size_mb: 50

spacy:
  model: "de_core_news_lg"
  auto_download: true

scraping:
  base_urls:
    - "https://amb.uni-leipzig.de/startseite-bekanntmachungen.html?kat_id=2001"
  download_directory: "./data/downloaded_pdfs"
  max_depth: 3
  timeout: 10

ui:
  title: "University Leipzig RAG Chat"
  page_icon: "🎓"
  layout: "centered"
  max_chat_history: 50

logging:
  level: "INFO" 
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/rag_system.log"

